title: Velherak
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
plugins:
  - jekyll-redirect-from

url: https://just-the-docs.github.io


logo: "/assets/images/TestLogoWeb.png"
favicon_ico: "/assets/images/faviconWhite.ico"

color_scheme: test


callouts:
  info:
    title: Info
    color: blue
    
search_enabled: false
search.button: false
